name: header file
description: This form is designed for users to easily record, document, and update metdata about BioEco ocean observing projects. Metadata recorded here will flow to the GOOS BioEco Portal and ODIS.
title: '[Add new BioEco metadata record]: '
assignees:
- EliLawrence
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to contribute your BioEco metadata. Your contributions help enhance our global understanding of ocean observations.
- type: markdown
  attributes:
    value: When you are sure the information recorded is complete, please add the "auto pr" label to the issue so the JSON-LD file will be generated for you.
- type: input
  id: project-name
  attributes:
    label: What is the name of the programme, project, or institution that will generate BioEco data?
    description: A name or title that best summarizes the programme or project.
    placeholder: BioEcoOcean
  validations:
    required: true
- type: input
  id: project-url
  attributes:
    label: What is the URL that links to programme/project?
    description: A complete URL that leads to a page describing the project
    placeholder: https://bioecoocean.org/
  validations:
    required: true
- type: input
  id: contact-name
  attributes:
    label: Point of Contact - Name
    description: Who is the best person (or organization) that someone can get in touch with if more info is needed?
    placeholder: 'examples: Alex Smith, OBIS Helpdesk'
  validations:
    required: true
- type: input
  id: contact-url
  attributes:
    label: Point of Contact - Email
    description: How can this contact point be reached?
    placeholder: ex. email@example.com
  validations:
    required: true
- type: textarea
  id: data-why
  attributes:
    label: Briefly describe the purposes and/or goals of the project.
    description: This description can be provided as an abstract.
    placeholder: A short abstract describing the project's purpose, goals, taxonomic and temporal extent,
  validations:
    required: false
- type: input
  id: start_date
  attributes:
    label: Start Date of Temporal Coverage
    description: "Enter the start date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: input
  id: end_date
  attributes:
    label: End Date of Temporal Coverage
    description: "Enter the end date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: input
  id: keywords
  attributes:
    label: Keywords
    description: Please list keywords associated with the programme.
    placeholder: ex. turtles, abundance
  validations:
    required: true
- type: input
  id: sops
  attributes:
    label: Standard Operating Procedures (SOPs)
    description: Please describe and/or link to SOPs that will be used to measure the EOV(s). 
  validations:
    required: true
- type: input
  id: output-url
  attributes:
    label: URLs for project outputs
    description: A list of complete URL(s) that leads to a page describing an output, e.g. dataset published to OBIS
    placeholder: http://ipt.iobis.org/obiscanada/resource?r=nuseds
  validations:
    required: false
- type: textarea
  id: geo-bounds
  attributes:
    label: Bounding Box
    description: Please provide a WKT string of points, lines and/or polygons that describes the area of the programme/project. The OBIS Maptool (https://obis.org/maptool/) can help generate WKT strings.
    placeholder: POLYGON ((-1.61499 56.36525, 2.51587 52.46940, 6.67969 54.43810, 6.25122 57.30872, -1.61499 56.36525))
  validations:
    required: false
- type: markdown
  attributes:
    value: '# EOV data collection metadata'
- type: markdown
  attributes:
    value: '---'
- type: markdown
  attributes:
    value: This section is for recording the metadata about the programme's data collection. For each category, there are dropdowns with multiple choices available. You may select all that apply.
- type: markdown
  attributes:
    value: If no options fit, please select "Any").
      
