name: Contribute BioEco metadata
description: This form is designed for users to easily record, document, and update
  metdata about BioEco ocean observing projects. Metadata recorded here will flow
  to the GOOS BioEco Portal and ODIS.
title: '[Add new BioEco metadata record]: '
assignees:
- EliLawrence
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to contribute your BioEco metadata. Your contributions
      help enhance our global understanding of ocean observations.
- type: input
  id: project-name
  attributes:
    label: What is the name of the project or institution that will generate BioEco
      data?
    description: A name or title that best summarizes the project.
    placeholder: BioEcoOcean
  validations:
    required: true
- type: input
  id: project-url
  attributes:
    label: What is the URL that links to project?
    description: A complete URL that leads to a page describing the project
    placeholder: https://bioecoocean.org/
  validations:
    required: true
- type: input
  id: contact
  attributes:
    label: Point of Contact
    description: Who is the best person (or organization) that someone can get in
      touch with if more info is needed?
    placeholder: ex. email@example.com
  validations:
    required: true
- type: textarea
  id: data-why
  attributes:
    label: Briefly describe the purposes and/or goals of the project.
    description: This description can be provided as an abstract.
    placeholder: A short abstract describing the project's purpose, goals, taxonomic
      and temporal extent,
  validations:
    required: false
- type: input
  id: start_date
  attributes:
    label: Start Date of Temporal Coverage
    description: "Enter the start date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: input
  id: end_date
  attributes:
    label: End Date of Temporal Coverage
    description: "Enter the end date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: input
  id: sops
  attributes:
    label: Standard Operating Procedures (SOPs)
    description: Please describe and/or link to SOPs that will be used to measure the EOV(s). 
  validations:
    required: true
- type: input
  id: output-url
  attributes:
    label: URLs for project outputs
    description: A list of complete URL(s) that leads to a page describing an output, e.g. dataset published to OBIS
    placeholder: http://ipt.iobis.org/obiscanada/resource?r=nuseds
  validations:
    required: false
- type: textarea
  id: geo-bounds
  attributes:
    label: Bounding Box
    description: Please provide a WKT string of points, lines and/or polygons that describes the area of the programme/project. The OBIS Maptool (https://obis.org/maptool/) can help generate WKT strings.
    placeholder: POLYGON ((-1.61499 56.36525, 2.51587 52.46940, 6.67969 54.43810, 6.25122 57.30872, -1.61499 56.36525))
  validations:
    required: false
- type: markdown
  attributes:
    value: '# EOV data collection metadata'
- type: markdown
  attributes:
    value: '---'
- type: markdown
  attributes:
    value: This section is for recording the metadata about the programme's data collection.
      For each category, there are dropdowns with multiple choices available. You
      may select all that apply.
- type: markdown
  attributes:
    value: If no options fit, please select "Any").
- type: dropdown
  id: license
  attributes:
    label: License
    description: Please select which Creative Commons license (https://creativecommons.org/share-your-work/cclicenses/) you expect the metadata and data to be made available.
    multiple: false
    options:
    - 0-CC0
    - 1-CC-BY
    - 2-CC-BY-SA
    - 3-CC-BY-NC
    - 4-CC-BY-NC-SA
    - 5-CC-BY-ND
    - 6-CC-BY-NC-ND
  validations:
    required: true
- type: dropdown
  id: eovs
  attributes:
    label: BioEco EOVs
    multiple: true
    options:
    - 0-Any
    - 1-Phytoplankton biomass and diversity
    - 2-Zooplankton biomass and diversity
    - 3-Fish abundance and distribution
    - 4-Marine turtles abundance and distribution
    - 5-Marine birds abundance and distribution
    - 6-Marine mammals abundance and distribution
    - 7-Hard coral cover and composition
    - 8-Seagrass cover and composition
    - 9-Macroalgal canopy cover and composition
    - 10-Mangrove cover and composition
    - 11-Microbe biomass and diversity
    - 12-Invertebrate abundance and distribution
  validations:
    required: true
- type: dropdown
  id: eovs-other
  attributes:
    label: Other EOVs
    multiple: true
    options:
    - 0-None
    - 1-Sea state
    - 2-Ocean surface stress
    - 3-Sea ice
    - 4-Sea surface height
    - 5-Sea surface temperature
    - 6-Subsurface temperature
    - 7-Surface currents
    - 8-Seagrass cover and composition
    - 9-Subsurface currents
    - 10-Sea surface salinity
    - 11-Subsurface salinity
    - 12-Ocean surface heat flux
    - 13-Ocean bottom pressure
    - 14-Oxygen
    - 15-Nutrients
    - 16-Inorganic carbon
    - 17-Transient tracers
    - 18-Particulate matter
    - 19-Nitrous oxide
    - 20-Stable carbon isotopes
    - 21-Dissolved organic carbon
  validations:
    required: true
- type: dropdown
  id: cregions
  attributes:
    label: Regions
    multiple: true
    options:
    - 0-Global
    - 1-Arctic Ocean
    - 2-Atlantic Ocean
    - 3-Baltic Sea
    - 4-High seas
    - 5-Indian Ocean
    - 6-Mediterranean Sea
    - 7-Pacific Ocean
    - 8-Southern Africa
    - 9-Southern Ocean
  validations:
    required: true
- type: dropdown
  id: cplatforms
  attributes:
    label: Observing Platforms
    multiple: true
    options:
    - 0-Any
    - 1-Buoy
    - 2-Platform
    - 3-Ship
    - 4-Airplane
    - 5-Satellite
    - 6-Floats
    - 7-CTDs
    - 8-Saildrone
    - 9-Drones
    - 10-Gliders
    - 11-Radar
    - 12-River Gauge
    - 13-Stations
    - 14-Surface Drifters
    - 15-Wave Gliders
  validations:
    required: true
- type: dropdown
  id: ebv
  attributes:
    label: Essential Biodiversity Variables
    multiple: true
    options:
    - 0-Any
    - 1-Genetic composition Genetic diversity
    - 2-Genetic composition Genetic differentiation
    - 3-Genetic composition Effective population size
    - 4-Genetic composition Inbreeding
    - 5-Species populations Species distributions
    - 6-Species populations Species abundances
    - 7-Species traits Morphology
    - 8-Species traits Physiology
    - 9-Species traits Phenology
    - 10-Species traits Movement
    - 11-Community composition Community abundance
    - 12-Community composition Taxonomic/phylogenetic diversity
    - 13-Community composition Trait diversity
    - 14-Community composition Interaction diversity
    - 15-Ecosystem functioning Primary productivity
    - 16-Ecosystem functioning Ecosystem phenology
    - 17-Ecosystem functioning Ecosystem disturbances
    - 18-Ecosystem structure Live cover fraction
    - 19-Ecosystem structure Ecosystem distribution
    - 20-Ecosystem structure Ecosystem Vertical Profile
    - 21-Algae Blooms
  validations:
    required: true
