name: Contribute BioEco metadata
description: This form is designed for users to easily record, document, and update
  metdata about BioEco ocean observing projects. Metadata recorded here will flow
  to the GOOS BioEco Portal and ODIS.
title: '[Add new BioEco metadata record]: '
assignees:
- EliLawrence
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to contribute your BioEco metadata. Your contributions
      help enhance our global understanding of ocean observations.
- type: markdown
  attributes:
    value: When you are sure the information recorded is complete, please add the
      "auto pr" label to the issue so the JSON-LD file will be generated for you.
- type: input
  id: project-name
  attributes:
    label: What is the name of the programme, project, or institution that will generate
      BioEco data?
    description: A name or title that best summarizes the programme or project.
    placeholder: BioEcoOcean
  validations:
    required: true
- type: input
  id: project-url
  attributes:
    label: What is the URL that links to programme/project?
    description: A complete URL that leads to a page describing the project
    placeholder: https://bioecoocean.org/
  validations:
    required: true
- type: input
  id: contact-name
  attributes:
    label: Point of Contact - Name
    description: Who is the best person (or organization) that someone can get in
      touch with if more info is needed?
    placeholder: 'examples: Alex Smith, OBIS Helpdesk'
  validations:
    required: true
- type: input
  id: contact-url
  attributes:
    label: Point of Contact - Email
    description: How can this contact point be reached?
    placeholder: ex. email@example.com
  validations:
    required: true
- type: textarea
  id: data-why
  attributes:
    label: Briefly describe the purposes and/or goals of the project.
    description: This description can be provided as an abstract.
    placeholder: A short abstract describing the project's purpose, goals, taxonomic
      and temporal extent,
  validations:
    required: false
- type: input
  id: start_date
  attributes:
    label: Start Date of Temporal Coverage
    description: Enter the start date of the project's temporal coverage (YYYY-MM-DD)
    placeholder: YYYY-MM-DD
  validations:
    required: true
- type: input
  id: end_date
  attributes:
    label: End Date of Temporal Coverage
    description: Enter the end date of the project's temporal coverage (YYYY-MM-DD)
    placeholder: YYYY-MM-DD
  validations:
    required: true
- type: input
  id: keywords
  attributes:
    label: Keywords
    description: Please list keywords associated with the programme.
    placeholder: ex. turtles, abundance
  validations:
    required: true
- type: input
  id: sops
  attributes:
    label: Standard Operating Procedures (SOPs)
    description: Please describe and/or link to SOPs that will be used to measure
      the EOV(s).
  validations:
    required: true
- type: input
  id: output-url
  attributes:
    label: URLs for project outputs
    description: A list of complete URL(s) that leads to a page describing an output,
      e.g. dataset published to OBIS
    placeholder: http://ipt.iobis.org/obiscanada/resource?r=nuseds
  validations:
    required: false
- type: textarea
  id: geo-bounds
  attributes:
    label: Bounding Box
    description: Please provide a WKT string of points, lines and/or polygons that
      describes the area of the programme/project. The OBIS Maptool (https://obis.org/maptool/)
      can help generate WKT strings.
    placeholder: POLYGON ((-1.61499 56.36525, 2.51587 52.46940, 6.67969 54.43810,
      6.25122 57.30872, -1.61499 56.36525))
  validations:
    required: false
- type: markdown
  attributes:
    value: '# EOV data collection metadata'
- type: markdown
  attributes:
    value: '---'
- type: markdown
  attributes:
    value: This section is for recording the metadata about the programme's data collection.
      For each category, there are dropdowns with multiple choices available. You
      may select all that apply.
- type: markdown
  attributes:
    value: If no options fit, please select "Any").
- type: dropdown
  id: license
  attributes:
    label: License
    description: Please select which Creative Commons license (https://creativecommons.org/share-your-work/cclicenses/)
      you expect the programme metadata to be made available.
    multiple: true
    options:
    - '0-CC0: Public Domain'
    - '1-CC-BY: Creative Commons Attribution 4.0'
    - '2-CC-BY-SA: Creative Commons Attribution Share Alike 4.0 International'
    - '3-CC-BY-NC: Creative Commons Attribution Non Commercial 4.0 International'
    - '4-CC-BY-NC-SA: Creative Commons Attribution Non Commercial Share Alike 4.0
      International'
    - '5-CC-BY-ND: Creative Commons Attribution No Derivatives 4.0 International'
    - '6-CC-BY-NC-ND: Creative Commons Attribution Non Commercial No Derivatives 4.0
      International'
  validations:
    required: false
- type: dropdown
  id: eovs
  attributes:
    label: BioEco EOVs
    description: Select the BioEco EOVs that the project aims to measure.
    multiple: true
    options:
    - 0-Phytoplankton biomass and diversity
    - 1-Zooplankton biomass and diversity
    - 2-Fish abundance and distribution
    - 3-Marine turtles abundance and distribution
    - 4-Marine birds abundance and distribution
    - 5-Marine mammals abundance and distribution
    - 6-Hard coral cover and composition
    - 7-Seagrass cover and composition
    - 8-Macroalgal canopy cover and composition
    - 9-Mangrove cover and composition
    - 10-Microbe biomass and diversity
    - 11-Invertebrate abundance and distribution
  validations:
    required: false
- type: dropdown
  id: eovs-other
  attributes:
    label: Other EOVs
    description: Select all relevant GOOS Physics, Biogeochemistry, and Cross-disciplinary
      EOVs
    multiple: true
    options:
    - 0-None
    - 1-Sea state
    - 2-Ocean surface stress
    - 3-Sea ice
    - 4-Sea surface height
    - 5-Sea surface temperature
    - 6-Subsurface temperature
    - 7-Surface currents
    - 8-Subsurface currents
    - 9-Sea surface salinity
    - 10-Subsurface salinity
    - 11-Ocean surface heat flux
    - 12-Turbulent diapycnal fluxes
    - 13-Ocean bottom pressure
    - 14-Oxygen
    - 15-Nutrients
    - 16-Inorganic carbon
    - 17-Transient tracers
    - 18-Particulate matter
    - 19-Nitrous oxide
    - 20-Stable carbon isotopes
    - 21-Dissolved organic carbon
    - 22-Ocean colour
    - 23-Ocean sound
  validations:
    required: false
- type: dropdown
  id: cregions
  attributes:
    label: Regions
    description: Which marine region(s) were sampled during the project? Select all
      that apply.
    multiple: true
    options:
    - 0-Global
    - 1-Arctic Ocean
    - 2-Atlantic Ocean
    - 3-Baltic Sea
    - 4-High seas
    - 5-Indian Ocean
    - 6-Mediterranean Sea
    - 7-Pacific Ocean
    - 8-Southern Africa
    - 9-Southern Ocean
  validations:
    required: false
- type: dropdown
  id: cplatforms
  attributes:
    label: Observing Platforms
    description: What types of Observing Platforms are used in the project? Select
      all that apply.
    multiple: true
    options:
    - 0-None
    - 1-Platform
    - 2-Ship
    - 3-Airplane
    - 4-Satellite
    - 5-Floats
    - 6-CTDs
    - 7-Saildrone
    - 8-Drones
    - 9-Gliders
    - 10-Radar
    - 11-River Gauge
    - 12-Stations
    - 13-Surface Drifters
    - 14-Wave Gliders
    - 15-Buoy
  validations:
    required: false
- type: dropdown
  id: ebv
  attributes:
    label: Essential Biodiversity Variables
    description: Select all relevant EBVs associated with the programme.
    multiple: true
    options:
    - 0-None
    - 1-Genetic composition Genetic diversity
    - 2-Genetic composition Genetic differentiation
    - 3-Genetic composition Effective population size
    - 4-Genetic composition Inbreeding
    - 5-Species populations Species distributions
    - 6-Species populations Species abundances
    - 7-Species traits Morphology
    - 8-Species traits Physiology
    - 9-Species traits Phenology
    - 10-Species traits Movement
    - 11-Community composition Community abundance
    - 12-Community composition Taxonomic/phylogenetic diversity
    - 13-Community composition Trait diversity
    - 14-Community composition Interaction diversity
    - 15-Ecosystem functioning Primary productivity
    - 16-Ecosystem functioning Ecosystem phenology
    - 17-Ecosystem functioning Ecosystem disturbances
    - 18-Ecosystem structure Live cover fraction
    - 19-Ecosystem structure Ecosystem distribution
    - 20-Ecosystem structure Ecosystem Vertical Profile
  validations:
    required: false
