name: Contribute BioEco metadata
description: This form is designed for users to easily record, document, and update metdata about BioEco ocean observing projects. Metadata recorded here will flow to the GOOS BioEco Portal and ODIS.
title: '[Add new BioEco metadata record]: '
assignees:
- EliLawrence
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to contribute your BioEco metadata. Your contributions help enhance our global understanding of ocean observations.
- type: input
  id: project-name
  attributes:
    label: What is the name of the project or institution that will generate BioEco data?
    description: A name or title that best summarizes the project.
    placeholder: BioEcoOcean
  validations:
    required: true
- type: input
  id: project-url
  attributes:
    label: What is the URL that links to project?
    description: A complete URL that leads to a page describing the project
    placeholder: https://bioecoocean.org/
  validations:
    required: true
- type: input
  id: contact
  attributes:
    label: Point of Contact
    description: Who is the best person (or organization) that someone can get in touch with if more info is needed?
    placeholder: ex. email@example.com
  validations:
    required: true
- type: textarea
  id: data-why
  attributes:
    label: Briefly describe the purposes and/or goals of the project.
    description: This description can be provided as an abstract.
    placeholder: A short abstract describing the project's purpose, goals, taxonomic and temporal extent,
  validations:
    required: false
- type: dropdown
  id: license
  attributes:
    label: License
    description: Please select which Creative Commons license (https://creativecommons.org/share-your-work/cclicenses/) you expect the metadata and data to be made available.
    multiple: false
    options:
    - 0-CC0
    - 1-CC-BY
    - 2-CC-BY-SA
    - 3-CC-BY-NC
    - 4-CC-BY-NC-SA
    - 5-CC-BY-ND
    - 6-CC-BY-NC-ND
  validations:
    required: true
- type: markdown
  attributes:
    value: '# EOV data collection metadata'
- type: markdown
  attributes:
    value: '---'
- type: markdown
  attributes:
    value: This section is for recording the metadata about the programme's data collection. For each category, there are dropdowns with multiple choices available. You may select all that apply.
- type: markdown
  attributes:
    value: If no options fit, please select "Any").
- type: dropdown
  id: eovs
  attributes:
    label: BioEco EOVs
    description: Select all relevant Biological and/or Ecosystem EOVs that the project aims to measure.
    multiple: true
    options:
    - 0-None
    - 1-Phytoplankton biomass and diversity
    - 2-Zooplankton biomass and diversity
    - 3-Fish abundance and distribution
    - 4-Marine turtles abundance and distribution
    - 5-Marine birds abundance and distribution
    - 6-Marine mammals abundance and distribution
    - 7-Hard coral cover and composition
    - 8-Seagrass cover and composition
    - 9-Macroalgal canopy cover and composition
    - 10-Mangrove cover and composition
    - 11-Microbe biomass and diversity
    - 12-Invertebrate abundance and distribution
  validations:
    required: true
- type: dropdown
  id: eovs-other
  attributes:
    label: Other EOVs
    description: Select all relevant GOOS Physics, Biogeochemistry, and Cross-disciplinary EOVs
    multiple: true
    options:
    - 0-None
    - 1-Sea state
    - 2-Ocean surface stress
    - 3-Sea ice
    - 4-Sea surface height
    - 5-Sea surface temperature
    - 6-Subsurface temperature
    - 7-Surface currents
    - 8-Seagrass cover and composition
    - 9-Subsurface currents
    - 10-Sea surface salinity
    - 11-Subsurface salinity
    - 12-Ocean surface heat flux
    - 13-Ocean bottom pressure
    - 14-Oxygen
    - 15-Nutrients
    - 16-Inorganic carbon
    - 17-Transient tracers
    - 18-Particulate matter
    - 19-Nitrous oxide
    - 20-Stable carbon isotopes
    - 21-Dissolved organic carbon
  validations:
    required: true
- type: input
  id: sops
  attributes:
    label: Standard Operating Procedures (SOPs)
    description: Please describe and/or link to SOPs that will be used to measure the EOV(s). 
  validations:
    required: true
- type: input
  id: start_date
  attributes:
    label: Start Date of Temporal Coverage
    description: "Enter the start date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: input
  id: end_date
  attributes:
    label: End Date of Temporal Coverage
    description: "Enter the end date of the project's temporal coverage (YYYY-MM-DD)"
    placeholder: "YYYY-MM-DD"
  validations:
      required: true
- type: dropdown
  id: cregions
  attributes:
    label: Regions
    description: Which region(s) were sampled during the project? Select all that apply.
    multiple: true
    options:
    - 0-Global
    - 1-Arctic Ocean
    - 2-Atlantic Ocean
    - 3-Baltic Sea
    - 4-High seas
    - 5-Indian Ocean
    - 6-Mediterranean Sea
    - 7-Pacific Ocean
    - 8-Southern Africa
    - 9-Southern Ocean
  validations:
    required: true
- type: input
  id: spatial-bound
  attributes:
    label: Bounding Box
    description: "To provide a WKT string of points, polygons, and/or line transects, please use this tool: https://obis.org/maptool/#. After populating the map with desired points, click the WKT button from this link and copy the string into the box below."
    placeholder: "POLYGON ((-1.61499 56.36525, 2.51587 52.46940, 6.67969 54.43810, 6.25122 57.30872, -1.61499 56.36525))"
  validations:
    required: false
- type: dropdown
  id: cplatforms
  attributes:
    label: Observing Platforms
    description: What types of Observing Platforms will be used in the project? Select all that apply.
    multiple: true
    options:
    - 0-Any
    - 1-Buoy
    - 2-Platform
    - 3-Ship
    - 4-Airplane
    - 5-Satellite
    - 6-Floats
    - 7-CTDs
    - 8-Saildrone
    - 9-Drones
    - 10-Gliders
    - 11-Radar
    - 12-River Gauge
    - 13-Stations
    - 14-Surface Drifters
    - 15-Wave Gliders
  validations:
    required: false
- type: dropdown
  id: cvar
  attributes:
    label: Variables
    description: What other variables does this project aim to measure? Select all that apply.
    multiple: true
    options:
    - 0-Any
    - 1-Sea Surface Temperature (SST)
    - 2-Sea Level Height
    - 3-Sea Level Pressure (SLP)
    - 4-Surface Pressure
    - 5-Currents
    - 6-Salinity
    - 7-Heat Fluxes
    - 8-Tidal
    - 9-Chlorphyll
    - 10-Mixed Layer Depth
    - 11-Waves
    - 12-Precipitation
    - 13-Sea-Ice
    - 14-Fish
    - 15-Wind Stress
    - 16-Evaporation
    - 17-Potential Temperature
    - 18-OLR
    - 19-Upwelling Indices
    - 20-Surface Temperature
    - 21-20C Isotherm
    - 22-Surface Winds
    - 23-Kelp and Seagrasses
    - 24-Algal Blooms
    - 25-Carbon
    - 26-Bathymetry
    - 27-Zooplankton
    - 28-Phytoplankton
    - 29-Oxygen
    - 30-Nitrates
    - 31-Bottom Temperature
    - 32-Clouds
    - 33-Heat Content
    - 34-DNA
    - 35-Density
    - 36-Coral
    - 37-Sea Mammals
    - 38-Atmosphere Variables
    - 39-Ocean Surface Variables
    - 40-Subsurface Ocean Variables
    - 41-Chemical Variables
    - 42-Marine Animal Variables
    - 43-Fish
    - 44-Marine Plant Variables
  validations:
    required: false
- type: dropdown
  id: ctopics
  attributes:
    label: Topics
    description: Select any topics that are relevant to the project.
    multiple: true
    options:
    - 0-Any
    - 1-ENSO
    - 2-MJO
    - 3-AMOC
    - 4-PDO
    - 5-Sea Level
    - 6-Climate Change
    - 7-Climate Indices
    - 8-Extremes
    - 9-Marine Heatwaves
    - 10-Arctic
    - 11-Hurricanes
    - 12-Air-Sea Interaction
    - 13-Upwelling
    - 14-Coastal Processes
    - 15-Inundation
    - 16-Economics
    - 17-Gulf Stream
    - 18-Wind Energy
    - 19-Indicators
    - 20-Resiliency
    - 21-Algae Blooms
  validations:
    required: false
- type: dropdown
  id: cproduct
  attributes:
    label: Product Types
    description: Select any product types your observation may relate to.
    multiple: true
    options:
    - 0-Any
    - '1-Values: Current'
    - '2-Values: Historic'
    - 3-Reanalysis
    - 4-Gridded Analysis
    - 5-Interactive Plotting Pages
    - 6-Forecasts
    - 7-Stations
    - 8-Animations
    - 9-In-situ
    - 10-Remote Sensing
    - 11-Data Guides/Repositories
    - 12-Code Repository
    - 13-Index Time-series
    - 14-Image/Animation Repository
    - 15-Educational
    - 16-International Data Repositories
    - 17-Analysis Tools
    - 18-ERDDAP Installations
    - 19-Reports
  validations:
    required: false
- type: input
  id: output-url
  attributes:
    label: URLs for project outputs
    description: A comma separated list of complete URL(s) leading to pages describing an output, e.g. dataset published to OBIS, a model output hosted on GitHub, etc.
    placeholder: http://ipt.iobis.org/obiscanada/resource?r=nuseds
  validations:
    required: false
