name: Contribute to the CEFI resource list
description: The form is designed for user to easily contribute to the CEFI resource list that will be used in the CEFI resource search portal
title: "[CEFI list contribution]: "
labels: ["contribution", "cefi_list"]
assignees:
  - chiaweh2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute to the CEFI resource list!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: data-why
    attributes:
      label: Tell us a bit about the data/resource!
      description: Why you think this data worth to be put into the CEFI resource list
      placeholder: A short sentence or paragraph on why you think the data/resource is important.
    validations:
      required: true
  - type: textarea
    id: data-title
    attributes:
      label: What is the best title for the data/resource?
      description: A title that best summarize the content.
      placeholder: Global Marine Heatwaves
    validations:
      required: true
  - type: textarea
    id: data-institute
    attributes:
      label: Who provide this data/resource?
      description: The institude/university/company that provide this data/resource
      placeholder: NOAA/PSL
    validations:
      required: true
  - type: dropdown
    id: data-type
    attributes:
      label: Analysis Type
      description: What Analysis Type is the data/resource?
      options:
        - 0 - Any
        - 1 - Accumulated precipitation
        - 2 - Anomaly
        - 3 - Climatology
        - 4 - Compare two datasets
        - 5 - Composite (average)
        - 6 - Correlation
        - 7 - ENSO relationships
        - 8 - Individual value
        - 9 - Ocean/Atmosphere time-series relationships
        - 10 - Data subsetting
        - 11 - Time-series
        - 12 - Regression
        - 13 - Seasonal Forecast
        - 14 - Time-section plots (Hovmoller)
        - 15 - Wavelet analysis
        - 16 - Sub seasonal forecast
        - 17 - Trajectory
        - 18 - Data Distributions
        - 19 - Animations
        - 20 - Profiles
        - 21 - Maps
    validations:
      required: false