- name: Contribute to the CEFI resource list test
- description: The form is designed for user to easily contribute to the CEFI resource
    list that will be used in the CEFI resource search portal
- title: '[CEFI list contribution]: '
- labels: 'cefi_contribution '
- assignees:
  - chiaweh2
- body:
  - type:
    - markdown
    - attributes:
      - value: Thanks for taking the time to contribute to the CEFI resource list!
