name: Add a resource
description: To add a resource
title: '[New Resource]: '
labels:
- new resource
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this bug report!

      '
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: A bug happened!
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of our software are you running?
    options:
    - 1.0.2 (Default)
    - 1.0.3 (Edge)
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically
      formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
- type: dropdown
  id: ctype
  attributes:
    label: Analysis Type
    multiple: 'True'
    options:
    - Any
    - Accumulated precipitation
    - Anomaly
    - Climatology
    - Compare two datasets
    - Composite (average)
    - Correlation
    - ENSO relationships
    - Individual value
    - Ocean/Atmosphere time-series relationships
    - Data subsetting
    - Time-series
    - Regression
    - Seasonal Forecast
    - Time-section plots (Hovmoller)
    - Wavelet analysis
    - Sub seasonal forecast
    - Trajectory
    - Data Distributions
    - Animations
    - Profiles
    - Maps
