name: Process Metadata Submission

on:
    workflow_dispatch:
    issues:
        types:
            - opened
            - edited
            - labeled

jobs:
  process_metadata_submission:
    
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Micromamba ${{ matrix.python-version }}
          uses: mamba-org/setup-micromamba@v2
          with:
            environment-file: environment.yml
            init-shell: bash
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
  
        - name: Install dependencies
          run: pip install --upgrade pip
  
        - name: Debug Issue Details
          run: |
            echo "Issue title: ${{ github.event.issue.title }}"
            echo "Issue body: ${{ github.event.issue.body }}"
            echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
  
        - name: Check for Metadata Submission Label
          if: contains(github.event.issue.labels.*.name, 'metadata submission')
          run: |
            python process_appsubmission.py \
              "${{ github.event.issue.title }}" \
              "${{ github.event.issue.body }}"
  
        - name: Commit and Push Changes
          if: contains(github.event.issue.labels.*.name, 'metadata submission')
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Add metadata for ${{ github.event.issue.title }}"
            git push
