name: PR check for JSON

on:
  pull_request:
     branches:
       - main
     paths:
       - 'data/cefi_list.json'

jobs:
  checking_json:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Activate MicroMamba Environment
        run: source activate cefi-info-hub

      - name: check JSON source
        shell: bash -l {0}
        run: |
          python check_json.py