name: Daily-linkcheck

on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '57 2 * * *'

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: link check
        shell: bash -l {0}
        run: pytest --verbose --check-links README.md
