name: Process Metadata Submission

on:
    workflow_dispatch:
    issues:
        types:
            - opened
            - edited
            - labeled

jobs:
  process_metadata_submission:
    
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
  
        - name: Install dependencies
          run: pip install --upgrade pip
  
        - name: Debug Issue Details
          run: |
            echo "Issue title: ${{ github.event.issue.title }}"
            echo "Raw issue body:"
            echo "${{ github.event.issue.body }}"
            issue_body="${{ github.event.issue.body }}"
            echo "$issue_body" | xxd
            sanitized_body=$(echo "$issue_body" | tr '\n' ' ' | sed -E 's/^### Metadata Submission//')
            echo "Sanitized issue body: $sanitized_body"
            echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
  
        - name: Check for Metadata Submission Label
          if: contains(github.event.issue.labels.*.name, 'metadata submission')
          run: |
            sanitized_body=$(echo "${{ github.event.issue.body }}" | tr '\n' ' ' | sed -E 's/^### Metadata Submission//')
            python process_appsubmission.py "${{ github.event.issue.title }}" "$sanitized_body"
  
        - name: Commit and Push Changes
          if: contains(github.event.issue.labels.*.name, 'metadata submission')
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git diff --quiet || git commit -m "Add metadata for ${{ github.event.issue.title }}"
            git push
