name: Generate Sitemap

on:
    workflow_dispatch:
    push:
        paths:
            - "JsonFiles/**"
    schedule:
        - cron: "0 0 * * 1"  # Weekly job to regenerate sitemap

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Download sitemap data
      uses: actions/download-artifact@v3
      with:
        name: sitemap-data
        path: sitemap_data/
      
    - name: Generate sitemap
      run: python generate_sitemap.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add sitemap.xml
        git commit -m "Update sitemap"
        git push
